---
name: Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Pulumi Preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198 # v1.0.0
        with:
          organization: muhlba91
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:muhlba91

      - uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions
      
      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952 # v6.0.0
        with:
          command: preview
          stack-name: prod
          refresh: true
        env:
          CLOUDSDK_COMPUTE_REGION: "${{ secrets.CLOUDSDK_COMPUTE_REGION }}"
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"
          GITHUB_TOKEN: "${{ secrets.GH_PAT_TOKEN }}"
          PROXMOX_VE_USERNAME: "${{ secrets.PROXMOX_VE_USERNAME }}"
          PROXMOX_VE_PASSWORD: "${{ secrets.PROXMOX_VE_PASSWORD }}"
          PROXMOX_VE_ENDPOINT: "${{ secrets.PROXMOX_VE_ENDPOINT }}"
          PROXMOX_VE_INSECURE: "${{ secrets.PROXMOX_VE_INSECURE }}"

  deploy:
    runs-on: ubuntu-latest
    name: Pulumi Deploy
    needs:
      - preview
    strategy:
      max-parallel: 12
      matrix:
        node-version: ["20"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - run: |
          corepack enable

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install --immutable
          yarn build

      - uses: pulumi/auth-actions@80dec0d5e009a11565cbf87d9ef9103fc7d24198 # v1.0.0
        with:
          organization: muhlba91
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:muhlba91

      - uses: tailscale/github-action@4e4c49acaa9818630ce0bd7a564372c17e33fb4d # v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions
      
      - uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952 # v6.0.0
        with:
          command: up
          stack-name: prod
        env:
          CLOUDSDK_COMPUTE_REGION: "${{ secrets.CLOUDSDK_COMPUTE_REGION }}"
          GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"
          GITHUB_TOKEN: "${{ secrets.GH_PAT_TOKEN }}"
          PROXMOX_VE_USERNAME: "${{ secrets.PROXMOX_VE_USERNAME }}"
          PROXMOX_VE_PASSWORD: "${{ secrets.PROXMOX_VE_PASSWORD }}"
          PROXMOX_VE_ENDPOINT: "${{ secrets.PROXMOX_VE_ENDPOINT }}"
          PROXMOX_VE_INSECURE: "${{ secrets.PROXMOX_VE_INSECURE }}"
